server.port=8077
spring.application.name=GestionReportes

# ===========================
#  PostgreSQL
# ===========================
spring.datasource.url=jdbc:postgresql://localhost:5432/gestion_reportesdb
spring.datasource.username=postgres
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===========================
#  URLs de otros microservicios
# ===========================
# Reparaciones
obrasmart.reparaciones.base-url=http://localhost:8084/reparaciones

# Stock
obrasmart.stock.repuestos-url=http://localhost:8085/api/repuestos
obrasmart.stock.movimientos-url=http://localhost:8085/api/movimientos

# Equipos
obrasmart.equipos.base-url=http://localhost:8082/equipos
