server.port=8077
spring.application.name=GestionReportes

spring.datasource.url=jdbc:postgresql://localhost:5432/gestion_reportesdb
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

obrasmart.equipos.base-url=http://localhost:8085/equipos
obrasmart.reparaciones.base-url=http://localhost:8085/reparaciones
obrasmart.stock.repuestos-url=http://localhost:8085/repuestos
obrasmart.stock.movimientos-url=http://localhost:8085/movimientos
