# ===============================
# CONFIGURACIÓN GENERAL
# ===============================

# Puerto del microservicio
server.port=8086

# ===============================
# BASE DE DATOS - PostgreSQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/gestion_reparacionesdb
spring.datasource.username=postgres
spring.datasource.password=123456

# ===============================
# HIBERNATE / JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# CLIENTE - GESTION EQUIPOS
# ===============================
# URL del microservicio GestionEquipos
clients.gestion-equipos.url=http://localhost:8087

# ===============================
# GEOLOCALIZACIÓN (Opcional)
# ===============================
# Clave API de LocationIQ (si la usas). Si está vacía, se usa Nominatim.
locationiq.key=
