# ===============================
# CONFIGURACI\u00D3N GENERAL
# ===============================

# Puerto del microservicio
server.port=8086

# ===============================
# BASE DE DATOS - PostgreSQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/gestion_reparacionesdb
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.connection-timeout=30000

# ===============================
# HIBERNATE / JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# CLIENTE - GESTION EQUIPOS
# ===============================
# URL del microservicio GestionEquipos
equipos.service.url=http://localhost:8087

# ===============================
# GEOLOCALIZACI\u00D3N (Opcional)
# ===============================
# Clave API de LocationIQ (si la usas). Si est\u00E1 vac\u00EDa, se usa Nominatim.
locationiq.key=
