server:
  port: 8083

spring:
  application:
    name: gestionstock

  datasource:
    url: jdbc:postgresql://localhost:5432/gestion_stockdb
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

logging:
  level:
    org.springframework.security: INFO
    org.springframework.web: INFO
