spring.application.name=GestionInspeccion
spring.datasource.url=jdbc:postgresql://localhost:5432/empleados
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
