spring.application.name=GestionDeLogin


spring.datasource.url=jdbc:postgresql://localhost:5432/obrasmartlogin
spring.datasource.username=postgres
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# JWT
jwt.secret=MI_SUPER_CLAVE_SECRETA_SEGURA_DE_32_CHARS!!!
jwt.expiration-ms=3600000
