# ==================================================
# CONFIG GENERAL
# ==================================================
server.port=8099
spring.application.name=GestionAsistente

logging.level.org.springframework=INFO
logging.level.com.ObraSmart=DEBUG

# ==================================================
# BOT INTERNO
# ==================================================
ia.bot.enabled=true

# ==================================================
# IA LOCAL (Ollama)
# ==================================================
ia.ollama.enabled=true
ia.ollama.url=http://localhost:11434/api/generate
ia.ollama.model=llama3.2:1b

# ==================================================
# IA CLOUD (Mistral)
# ==================================================
ia.cloud.enabled=true
ia.cloud.url=https://api.mistral.ai/v1/chat/completions
ia.cloud.apikey=WUzheB9Dty6AYKOdR2zqWSqIsZF66jbE
ia.cloud.model=mistral-small-latest

# ==================================================
# UTF-8
# ==================================================
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
